#!/bin/sh

set -e

if ! command -v aws > /dev/null
then
    echo "AWS CLI could not be found. Cannot continue"
    exit 1
fi

if ! command -v jq > /dev/null
then
    echo "JQ could not be found. Cannot continue"
    exit 1
fi

ROLE_ARN=$1
SESSION_NAME=${2:-assumerole}

if [ -z "${ROLE_ARN}" ]; then
  echo "role arn is needed as the 1st argument"
  exit 1
fi

ASSUME_ROLE_RESULT=$(aws sts assume-role --role-arn "${ROLE_ARN}" --role-session-name "${SESSION_NAME}" --output json)

ACCESS_KEY_ID=$(echo "${ASSUME_ROLE_RESULT}" | jq -r ".Credentials.AccessKeyId" )
SECREK_ACCESS_KEY=$(echo "${ASSUME_ROLE_RESULT}" | jq -r ".Credentials.SecretAccessKey" )
SESSION_TOKEN=$(echo "${ASSUME_ROLE_RESULT}" | jq -r ".Credentials.SessionToken" )

echo "export AWS_ACCESS_KEY_ID=${ACCESS_KEY_ID}"
echo "export AWS_SECRET_ACCESS_KEY=${SECREK_ACCESS_KEY}"
echo "export AWS_SESSION_TOKEN=${SESSION_TOKEN}"
